"""Add thread_id column

Revision ID: cbbfaac5d06d
Revises: 
Create Date: 2025-07-30 22:37:04.880180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbbfaac5d06d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###
